output:
  - format: asciidoc
  - format: epub
  - format: html
  - format: pdf
generate_landingpage: true
content-files:
  - introduction.md
  - chapter01.md
  - chapter02.md
  - chapter03.md
  - chapter04.md
  - appendix.md
